global using static SDL2.SDL;
global using static SDL2.SDL_image;
global using static SDL2.SDL_mixer;
global using static SDL2.SDL.SDL_EventType;
global using static SDL2.SDL_ttf;
global using static SDL2.SDL.SDL_Keycode;
global using static SDL2.SDL_image.IMG_InitFlags;
global using static SDL2.SDL.SDL_WindowFlags;
global using static SDL2.SDL.SDL_bool;
global using static SDL2.SDL.SDL_WindowEventID;
global using static SDL2.SDL.SDL_Keymod;
global using static SDL2.SDL.SDL_BlendMode;
global using static SDL2.SDL.SDL_RendererFlags;
global using System;
global using System.Threading;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using System.Drawing;
global using System.Linq;
global using System.Collections.ObjectModel;
global using System.Text;
global using System.Text.Json;
